[package]
name = "symbol"
version = "0.1.0"
edition = "2021"
authors = [ "Luca Lewin <contact@lucalewin.dev>" ]

[dependencies]
thiserror = "1.0.59"
num = "0.4.2"
chumsky = "0.9.3"
# logos = "0.14.0"
once_cell = "1.19.0"
iter_tools = "0.15.0"
log = "0.4.21"
env_logger = "0.11.3"